build-containers.yml: Limit Anisble core version to 2.20
Ansible core needs to stay at 2.20 for now to be able to build the
container for ansible-freeipa testing on Fedora Rawhide.

ansible.legacy.setup is not usable with Ansible core 2.21:

ansible/module_utils/_internal/_patches/__init__.py, line 45,
    in get_current_implementation\nAttributeError: module
    'dataclasses' has no attribute '_is_type'